// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL5e-iy5UkRX3J0_xFzLTEfkMy-88gbh8',
    appId: '1:232513278876:web:850eba6866248974852e59',
    messagingSenderId: '232513278876',
    projectId: 'interntask1-87e2c',
    authDomain: 'interntask1-87e2c.firebaseapp.com',
    storageBucket: 'interntask1-87e2c.appspot.com',
    measurementId: 'G-WW05GZ44KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBllqTbI7eWn3gjz6T7G0OTPn6spQzgPYM',
    appId: '1:232513278876:android:bfe46719bb2aab1c852e59',
    messagingSenderId: '232513278876',
    projectId: 'interntask1-87e2c',
    storageBucket: 'interntask1-87e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirYi6eeYY8Z3dHSfYxO-6PLRoPgaoZIk',
    appId: '1:232513278876:ios:c627cea8b15dd0b6852e59',
    messagingSenderId: '232513278876',
    projectId: 'interntask1-87e2c',
    storageBucket: 'interntask1-87e2c.appspot.com',
    iosClientId: '232513278876-v6hcghelgqt94bkcpjo1tkgphd2onrkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.internTask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirYi6eeYY8Z3dHSfYxO-6PLRoPgaoZIk',
    appId: '1:232513278876:ios:c627cea8b15dd0b6852e59',
    messagingSenderId: '232513278876',
    projectId: 'interntask1-87e2c',
    storageBucket: 'interntask1-87e2c.appspot.com',
    iosClientId: '232513278876-v6hcghelgqt94bkcpjo1tkgphd2onrkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.internTask1',
  );
}
